baseURL = "https://beengo.github.io/"
title = "Beengo"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "ExampleSite"
description = "ExampleSite description"
keywords = ["Blog", "Portfolio", "PaperMod"]
author = "beengo"
images = ["<link or path of image for opengraph, twitter-cards>"]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.assets]
favicon = "<link / abs url>"
favicon16x16 = "<link / abs url>"
favicon32x32 = "<link / abs url>"
apple_touch_icon = "<link / abs url>"
safari_pinned_tab = "<link / abs url>"

[params.label]
text = "Home Title"
icon = "/apple-touch-icon.png"
iconHeight = 35

[params.profileMode]
enabled = false
title = "ExampleSite"
subtitle = "This is subtitle"
imageUrl = "<img location>"
imageWidth = 120
imageHeight = 120
imageTitle = "my image"

[[params.profileMode.buttons]]
name = "Posts"
url = "posts"

[[params.profileMode.buttons]]
name = "Tags"
url = "tags"

[params.homeInfoParams]
Title = "Hi!"
Content = "Coming soon"

[[params.socialIcons]]
name = "github"
url = "https://github.com/beengo"


[params.cover]
hidden = true
hiddenInList = true
hiddenInSingle = true

# [params.editPost]
# URL = "https://github.com/<path_to_repo>/content"
# Text = "Suggest Changes"
# appendFilePath = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
limit = 10
keys = ["title", "permalink", "summary", "content"]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "game"
name = "Game"
url = "/game/"
weight = 20

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 30

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 40

[markup.highlight]
noClasses = false
